# Generated by Django 4.1.3 on 2022-12-29 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headpic', models.URLField(blank=True, max_length=3000, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('h1', models.CharField(blank=True, max_length=100, null=True)),
                ('p1', models.TextField(blank=True, null=True)),
                ('pic1', models.URLField(blank=True, max_length=3000, null=True)),
                ('h2', models.CharField(blank=True, max_length=100, null=True)),
                ('p2', models.TextField(blank=True, null=True)),
                ('qt1', models.CharField(blank=True, max_length=500, null=True)),
                ('pic2', models.URLField(blank=True, max_length=3000, null=True)),
                ('h3', models.CharField(blank=True, max_length=100, null=True)),
                ('p3', models.TextField(blank=True, null=True)),
                ('qt3', models.CharField(blank=True, max_length=500, null=True)),
                ('pic3', models.URLField(blank=True, max_length=3000, null=True)),
                ('h4', models.CharField(blank=True, max_length=100, null=True)),
                ('p4', models.TextField(blank=True, null=True)),
                ('qt4', models.CharField(blank=True, max_length=500, null=True)),
                ('pic4', models.URLField(blank=True, max_length=3000, null=True)),
                ('h5', models.CharField(blank=True, max_length=100, null=True)),
                ('p5', models.TextField(blank=True, null=True)),
                ('qt5', models.CharField(blank=True, max_length=500, null=True)),
                ('pic5', models.URLField(blank=True, max_length=3000, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('slug', models.SlugField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_category')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.blog_main')),
            ],
        ),
    ]
