# Generated by Django 4.1.3 on 2022-12-29 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('is_ad', models.BooleanField(default=False)),
                ('varified', models.BooleanField(blank=True, default=False)),
                ('Fresher', models.BooleanField(default=False, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('vaccancy', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='job_images')),
                ('availability', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('yoursite', models.URLField(blank=True, null=True)),
                ('job_disc', models.TextField()),
                ('skill', models.CharField(blank=True, max_length=30, null=True)),
                ('skills', models.TextField()),
                ('edu_experience', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.categories')),
            ],
        ),
    ]
