# Generated by Django 4.1.3 on 2022-12-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='job_images'),
        ),
    ]
