# Generated by Django 4.1.3 on 2022-12-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_job_options_alter_job_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='job_images'),
        ),
    ]
