# Generated by Django 4.1.3 on 2023-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_job_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applyurl',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='photourl',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_disc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
