# Generated by Django 4.1.3 on 2023-02-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_job_applyurl_job_photourl_alter_job_job_disc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='city',
        ),
    ]
